# escape=`
{% if render_phase.bootstrap %}
{{ bootstrap.recipe }}

{% endif %}
{% if render_phase.build %}
# Build stage with Spack pre-installed and ready to be used
FROM {{ build.image }} AS builder

{% block build_stage %}

SHELL ["cmd", "/S", "/C"]
# What we want to install and how we want to install it
# is specified in a manifest file (spack.yaml)
RUN mkdir {{ paths.environment }}`
{{ manifest }} > {{ paths.environment }}\spack.yaml

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

# Install the software, remove unnecessary deps
RUN cd {{ paths.environment }} -AND spack env activate . -AND spack install --fail-fast -AND spack gc -y

# Modifications to the environment that are necessary to run
RUN cd {{ paths.environment }} -AND `
    spack env activate --pwsh -d . > activate.ps1

{% endblock build_stage %}
{% endif %}

{% if render_phase.final %}
# Bare OS image to run the installed executables
FROM {{ run.image }}

COPY --from=builder {{ paths.environment }} {{ paths.environment }}
COPY --from=builder {{ paths.store }} {{ paths.store }}

# paths.view is a symlink, so copy the parent to avoid dereferencing and duplicating it
COPY --from=builder {{ paths.view_parent }} {{ paths.view_parent }}

SHELL ["cmd", "/S", "/C"]

RUN ( `
      echo . {{ paths.environment }}/activate.ps1 `
      && echo $args; `
    ) > entrypoint.ps1 `
    && mklink {{ paths.former_view }} {{ paths.view }}

{% for label, value in labels.items() %}
LABEL "{{ label }}"="{{ value }}"
{% endfor %}
ENTRYPOINT [ "/entrypoint.ps1" ]
CMD [ "powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';" ]
{% endif %}
