name: integration tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - develop
      - releases/**

concurrency:
  group: intergrations-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    outputs:
      install_jobs: ${{ steps.scan-tests.integration_tests }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        if: ${{ github.event_name == 'push' || github.event_name == 'merge_group' }}
        with:
          fetch-depth: 0
      # - name: "Add Integration test repo"
      #   run: |
      #     . share/spack/setup-env.sh
      #     spack config --scope user add repos:builtin:git:'https://github.com/johnwparent/spack-integration-test-repo.git'
      - name: "List repo packages"
        id: scan-tests
        run: |
          . share/spack/setup-env.sh
          packages_list="$(spack list | tr '\n' ',')"
          echo "packages=${packages_list}" >> "$GITHUB_OUTPUT" 

  run:
    needs: scan
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, macos-13, macos-14, windows-latest]
    #     package: [ ${{ needs.scan.outputs.install_jobs }}, "a" ] # list of spack intergration test packages to run
    steps:
      # - name: "Spack install"
      #   run: |
      #     spack install ${{ matrix.package }}
      - name: "matrix check"
        run: |
          echo ${{ needs.scan.outputs.install_jobs }}
